version: 0.0
os: linux
#source: / => 전체경로받기
#destination : 본인 ec2 디렉토리구조
files:
  - source: /
    destination: /home/ubuntu/node-express-mysql-swagger
    overwrite: yes

permissions:
  - object: /home/ubuntu
    pattern: '**'
    owner: ubuntu
    group: ubuntu

#BeforeInstall, AfterInstall(codeDeploy 수명주기)에 실행될 파일 지정
hooks:
  BeforeInstall:
    - location: /deploy_script/before_deploy.sh
      runas: ubuntu
  AfterInstall:
    - location: /deploy_script/after-deploy.sh
      timeout: 180
      runas: ubuntu